---
title: Conor Higgins' Resume"
author: Conor Higgins
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['css/custom_resume.css', 'css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---


```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(tidyverse)
library(glue)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- TRUE

# Holds all the links that were inserted for placement at the end
links <- c("https://twitter.com/conormjhiggins","https://github.com/conormjhiggins")

source('parsing_functions.R')


# First let's get the data, filtering to only the items tagged as
# Resume items
position_data <- read_csv('positions.csv') %>% 
  filter(in_resume) %>% 
  mutate(
    # Build some custom sections by collapsing others
    section = case_when(
      section %in% c('research_positions', 'industry_positions') ~ 'positions', 
      section %in% c('data_science_writings', 'by_me_press') ~ 'writings',
      TRUE ~ section
    )
  ) 

```


Aside
================================================================================




Contact {#contact}
--------------------------------------------------------------------------------



- <i class="fa fa-envelope"></i> conormjhiggins@gmail.com
- <i class="fa fa-twitter"></i> [conormjhiggins](https://twitter.com/conormjhiggins)
- <i class="fa fa-github"></i> [github.com/conormjhiggins](https://github.com/conormjhiggins)
- <i class="fa fa-phone"></i> (+44) 7728 434048



Language & Visualisation Skills {#skills}
--------------------------------------------------------------------------------

Highly Skilled & Experienced

- SQL (Predominantly on Snowflake)
- dbt
- Airflow 
- Python
- R
- git
- bash
- Looker
- Tableau
- PowerBI
- MS Office Suite

Experience With & Learning

- AWS 
- Docker
- HTML
- CSS
- Fivetran
- Kubernetes
- Prefect


More Info {#more-info}
--------------------------------------------------------------------------------

Made w/ [**pagedown**](https://github.com/rstudio/pagedown). 

Source code: [github.com/conormjhiggins/cv](https://github.com/conormjhiggins/cv).

Last updated on `r Sys.Date()`.




Main
================================================================================

Conor Higgins {#title}
--------------------------------------------------------------------------------

```{r}
intro_text <- 

"I am an outstanding communicator and leader with high levels of determination and motivation. 
Excellent ability to bring enthusiasm, focus, and a positive demeanor to the workplace.
Flexible, dependable, and eager to work both independently as well as in a team towards goals. 
I am a confident public speaker and collaborator,
as evidenced by my participation in and leadership of many teams through both my extra-curricular and work experiences. 
I am a problem solver and I am confident I would be a valuable asset to any team."

cat(sanitize_links(intro_text))
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('education')
```



Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('positions')
```